services:
  ollama:
    image: 'ollama/ollama:latest'
    ports:
      - '11434'
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=tgnews
      - POSTGRES_PASSWORD=temp
      - POSTGRES_USER=temp
    ports:
      - '5432'

networks:
  tgnews-network:
    driver: bridge